#!/bin/bash
#VERSION=1.6####################################################################
# Revision Log
# VERSION=0.0 - Conversion works
# VERSION=0.1 - Rename Function added
# VERSION=0.2 - HandBrakeCLI installed check
# VERSION=0.3 - ReFormatted Code into functions
# VERSION=0.4 - Added download link to Install Check
# VERSION=0.5 - Corrected Rename function
# VERSION=0.6 - Adding more video formats to rename function
# VERSION=0.7 - Added OS Check to work with both LINUX and MAC OSX
# VERSION=0.8 - Added a check before renames to verify file type existance
# VERSION=0.9 - Added color to the COMPLETE statement
# VERSION=1.0 - Added mpeg format to rename function
# VERSION=1.1 - Remove source files, via confirmation
# VERSION=1.2 - Remove source files, without individual file confirmation
# VERSION=1.3 - Removed Comments
# VERSION=1.4 - Adding extra checking to remove_src function
# VERSION=1.5 - Working on self updating
# VERSION=1.6 - Removed rename function, was able to do rename within convert function
################################################################################
# This script converts any kind of video the HandBrake CLI can handle
# into a 1000 kbit MPEG4 video and shrinks it down to a max width of 640 px.
#
# Usage:
# Running the script without any parameters just uses *all* files in the
# ToBeConverted directory and converts them, so make sure you only have video
# files in that directory.
#
# You can specify an input and output directory if you want:
# 'script <INPUT> <OUTPUT>'
################################################################################
################################
########Color Variables#########
################################
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

################################
###########OS Check#############
################################
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
   platform='Darwin'
   IN=$HOME/Desktop/ToBeConverted
   OUT=$HOME/Desktop/Converted
   if [ -f $IN ]; then
     mkdir -p $IN
     echo "Creating $IN"
   fi
   if [ -f $OUT ]; then
     mkdir -p $OUT
     echo "Creating $OUT"
   fi

elif [[ "$unamestr" == 'Linux' ]]; then
   platform='Linux'
   IN=$HOME/ToBeConverted
   OUT=$HOME/Converted
   if [ ! -f $IN ]; then
     mkdir -p $IN
     echo "Creating $IN"
   fi
   if [ ! -f $OUT ]; then
     mkdir -p $OUT
     echo "Creating $OUT"
   fi
fi

################################
###HandBrakeCLI install check###
################################
if [[ "$platform" == 'Darwin' ]]; then
  if [ ! -f /usr/local/bin/HandBrakeCLI ]; then
    echo "HandBrakeCLI IS NOT INSTALLED!"
    echo "Download Here: https://handbrake.fr/downloads2.php"
    echo "Save HandBrakeCLI to /usr/local/bin"
    exit 1
  fi
fi
if [[ "$platform" == 'Linux' ]]; then
  if [ ! -f /usr/bin/HandBrakeCLI ]; then
    echo "HandBrakeCLI IS NOT INSTALLED!"
    echo "Download Here: https://handbrake.fr/downloads2.php"
    echo "Save HandBrakeCLI to /usr/local/bin"
    exit 1
  fi
fi

################################
#####Check Converted folder#####
################################
function pre_convert {
  list_convert=`ls $OUT | wc -l`
  if [[ list_convert > 0 ]]; then
    echo "Cleanup Converted Directory"
    exit 0
  fi
}

################################
######Conversion Function#######
################################
function convert {
    #Use global Variables for INPUT and OUTPUT
    cd "$IN"
    for InputItem in *;do
      /usr/local/bin/HandBrakeCLI -i "$InputItem" -o "$OUT/${InputItem%\.[^.]*}.mp4" --preset="Fast 1080p30" -f mp4
    done
}

################################
######Remove Source Files#######
################################
function remove_src {
  ToBeCount=`ls -l $IN 2>/dev/null | wc -l`
  ConvertCount=`ls -l $OUT 2>/dev/null | wc -l`
  if [ $ToBeCount == $ConvertCount ]; then
    rm -f $IN/* #Using -f to make sure it doesn't confirm
    echo "${green}
     #####  #     #  #####   #####  #######  #####   #####
    #     # #     # #     # #     # #       #     # #     #
    #       #     # #       #       #       #       #
     #####  #     # #       #       #####    #####   #####
          # #     # #       #       #             #       #
    #     # #     # #     # #     # #       #     # #     #
     #####   #####   #####   #####  #######  #####   #####
    ${reset}"
  else
    echo "${red}Source Files Were not removed${reset}"
  fi
}

#Main
convert
remove_src

exit 0
